### ISSUE TITLE
Issue with getting time from adafruit IO?

### ISSUE THREAD

**Issue by rpavlik** [adafruit/Adafruit_CircuitPython_MatrixPortal#34]
Testing with today's library bundle and cp6.0.0rc0, on a new Matrix Portal M4. I can connect to aio and send data, per the learn guide, but neither of the clock-related samples I tried work: both fail with the following (truncated) serial log.

```
Getting time for timezone America/Chicaco
Socket missing recv_into. Using more memory to be compatible
Traceback (most recent call last):
  File "code.py", line 98, in <module>
  File "code.py", line 95, in <module>
  File "adafruit_matrixportal/network.py", line 198, in get_local_time
  File "adafruit_matrixportal/network.py", line 186, in get_local_time
ValueError: Error connection to Adafruit IO. The response was: {"error":"request failed - failed to generate strftime with given format"}
```

I get the same error with both of these:

- https://learn.adafruit.com/halloween-countdown-display-matrix/code-the-halloween-countdown
- https://learn.adafruit.com/network-connected-metro-rgb-matrix-clock/code-the-matrix-clock

**Comment by siddacious** [comment]
@rpavlik I suspect the issue is your time zone "America/Chicaco", which should presumably be "America/Chicago"

edit: If that doesn't fix the issue, let us know and I'll re-open the issue and dig into it more
