### ISSUE TITLE
Text Position Required With Scrolling

### ISSUE THREAD

**Issue by jammininmypjs** [adafruit/Adafruit_CircuitPython_MatrixPortal#35]
https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/blob/6646a23130426e7076e119e023cb20a33bf9328c/adafruit_matrixportal/matrixportal.py#L182

When I try to add_text to the MatrixPortal I get the error:

```
      File "code.py", line 85, in <module>
      File "code.py", line 70, in init_matrixportal
      File "adafruit_matrixportal/matrixportal.py", line 182, in add_text
    TypeError: 'NoneType' object is not subscriptable
```

https://forums.adafruit.com/viewtopic.php?f=60&t=171208&p=836374#p836374

In the support forums, it was determined the above line of code is expecting that you also provide the text_position parameter when specifying scrolling

**Comment by makermelissa** [comment]
Yeah, we should probably check for this when the text is added so the user has a more friendly error.
