### ISSUE TITLE
Issue running code from README.md

### ISSUE THREAD

**Issue by lastcoolnameleft** [adafruit/Adafruit_CircuitPython_MatrixPortal#39]
When I try running the code from the Repo's README, I get the following:

```
Traceback (most recent call last):
  File "code.py", line 29, in <module>
TypeError: 'module' object is not callable
```

I'm using: adafruit-circuitpython-matrixportal_m4-en_US-6.0.0-rc.1.uf2 and adafruit-circuitpython-bundle-6.x-mpy-20201105

**Comment by makermelissa** [comment]
Thanks. Looks like it needs to be updated. It should basically be the same as https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/blob/master/examples/matrixportal_simpletest.py
