### ISSUE TITLE
SUGGESTION:  A more basic "hello world" for the board.

### ISSUE THREAD

**Issue by lastcoolnameleft** [adafruit/Adafruit_CircuitPython_MatrixPortal#41]
For the example in the main README, I recommend something that's a bit more basic.  I don't know if this is typical, but the example in the README takes ~3-5 seconds before the screen displays the value (I also don't see any serial text for this example. Not sure why.) Many times I thought it wasn't working because nothing was happening, but it was just the delay.  As a new user that is confusing.

Setting a datasource is great, but as a new user, I want to start with something basic and build from there.

Here is a really basic sample which I think is a good "hello world" for the board:
https://gist.github.com/lastcoolnameleft/3e747626461a191741df8c5f4e57868e

Thoughts?

**Comment by FoamyGuy** [comment]
I do think it would be good to include a more basic simple test example that doesn't rely on internet access. I like the idea of using it in the readme as well, but we can see if anyone else has thoughts. 

As a start you could make a PR adding that to the examples directory if you want.

**Comment by makermelissa** [comment]
I think it’s a good idea. The original “simpletest” was developed before a lot of the auto detect code and various guides were in place.

**Comment by makermelissa** [comment]
Fixed via #45.
