### ISSUE TITLE
Issue initializing both MatrixPortal and Network results in ValueError: ESP_BUSY in use

### ISSUE THREAD

**Issue by EduTechTools** [adafruit/Adafruit_CircuitPython_MatrixPortal#42]
I'm attempting to send data from a Stemma QT connected device to Adafruit IO and load a background onto the 16x32 Matrix using the Matrix Portal.  I've simplifed the code down to where the error occurs.

```
import board
from adafruit_matrixportal.network import Network
from adafruit_matrixportal.matrixportal import MatrixPortal

matrixportal = MatrixPortal()
network = Network(status_neopixel=board.NEOPIXEL, debug=False)
```
Results in:
```
code.py output:
Set background to  0
Traceback (most recent call last):
  File "code.py", line 6, in <module>
  File "adafruit_matrixportal/network.py", line 107, in __init__
  File "adafruit_matrixportal/wifi.py", line 65, in __init__
ValueError: ESP_BUSY in use
```

**Comment by FoamyGuy** [comment]
I think you could re-use the network object made inside matrixportal instead of making another one. Try like this:
```python
matrixportal = MatrixPortal()
network = matrixportal.network
```

**Comment by EduTechTools** [comment]
@FoamyGuy Thanks.  (Lesson learned: review the library code before posting an issue)

I was successful in reusing the network object inside matrixportal.
