### ISSUE TITLE
fetch_data doesn’t close the response, leading to a leak

### ISSUE THREAD

**Issue by fionawhim** [adafruit/Adafruit_CircuitPython_MatrixPortal#56]
I was noticing that the [Weather Display Matrix](https://learn.adafruit.com/weather-display-matrix) demo freezes after a few hours. The output is a loop of:

```
Getting time from internet!
Getting time for timezone America/New_York
Some error occured, retrying! - No sockets available
```

Looking over the `network.py` code, it seems that `fetch_data` (which the demo uses to get weather data) doesn’t explicitly close the `response` object, which may be leading to the leak of sockets on the ESP32. (And therefore prevent the time call from succeeding.)

Should there be a `response.close()` call right above setting `response = None`, following the same pattern as in `get_local_time`?

**Comment by tannewt** [comment]
An extra .close() should be fine. Requests should close the previous response when a new request is made though.

What versions of the libraries are you using?

**Comment by fionawhim** [comment]
@tannewt Ah, cool. I didn’t dig into the `requests` library to see it clean up after the last request.

TBH this bug was showing up in what I think was a mix of 10/31 libraries and some from 12/5. I’ve updated everything to the 12/22 and have it running now. It’ll take a few hours to see if it reproduces.

I don’t have the logs saved, but I remember seeing an exception bubble up to the retry loop in `code.py` (something like “tried to send 3 bytes, sent 0” or something along those lines).

If the `requests` library on the board pre-dated your error handling overhaul in early November, that could explain the source of the socket leak, if those erroring sockets weren’t cleaned up right. I’m not seeing the same message with updated libraries.

Thanks for everyone’s attention and looking at this. Apologies that I didn’t try updating libraries before reporting. I jumped to the conclusion about where the bug was after not seeing `request.close()` in the latest Matrix Portal code.

**Comment by makermelissa** [comment]
I have a refactor PR in place for this library. I'll be sure to add this to the refactor.

**Comment by fionawhim** [comment]
Closing as not reproducable with the latest versions of the libraries. There’s no longer a leak of ESP32 sockets.

**Comment by Lnk2past** [comment]
I am seeing this on my end as well - explicitly closing the response at the end of `fetch_data` resolved the issue for me.

**Comment by makermelissa** [comment]
@Lnk2past please update your libraries and try again. I refactored PortalBase yesterday and I'm not sure if it's still an issue. If so, I'll re-open and move this issue to PortalBase as that's where the applicable code now resides.

**Comment by Lnk2past** [comment]
Thanks @makermelissa! This is no longer an issue!
