### ISSUE TITLE
Calling matrixportal more than once

### ISSUE THREAD

**Issue by hifarrer** [adafruit/Adafruit_CircuitPython_MatrixPortal#60]
Hi! I made a stocks version using your bitcoin example.
It currently works fine with just 1 stock, but I wanted to scroll from a list of multiple stocks, ie: "GME","APPL","BB" etc
The problem is that when I call the function it only works on first try, after that I keep getting: NEOPIXEL in use.

So in other words, I can't figure out how to call this:
` matrixportal = MatrixPortal(
        url=DATA_SOURCE,
        json_path=DATA_LOCATION,
        status_neopixel=board.NEOPIXEL,
        default_bg=cwd + "/GME_background.bmp",
        debug=True,
    )`
Multiple times, without getting that NEOPIXEL in use.

I hope there is a way to just reset it or something like that.
Thanks!

**Comment by hifarrer** [comment]
I think it would be the same as trying to add multiple coins to your bitcoin project, like ETH, LTC.
Coins = "BTC", "LTC", "ETH"
And just loop through them displaying the info.

**Comment by caternuson** [comment]
You should only ever create one instance of the MatrixPortal object in your code. That means, only one line that looks like:
```python
matrixportal = MatrixPortal( ..arguments go here.. )
```
After that, you do everything using `matrixportal`. For multiple stocks, you'll need to do something like parse the return from `fetch()` or change the data location to different stocks and call `fetch()` multiple times.

**Comment by makermelissa** [comment]
You'll want to just call add_text() more than once.

**Comment by hifarrer** [comment]
Thank you very much, you both pointed me to the right direction and now I'm able to change the text using 1 instance.

**Comment by caternuson** [comment]
Cool. Glad that helped and you got it working.
