### ISSUE TITLE
Possible Rotation

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_MatrixPortal#63]
So it looks like framebufferio has a rotation property (https://circuitpython.readthedocs.io/en/latest/shared-bindings/rgbmatrix/index.html) that we have not been taking advantage of. I think it might be possible to add rotation to this library by making use of that.

**Comment by kmatch98** [comment]
here’s the link from the MatrixPortal down to FrameBufferIO:

https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/blob/90524923861c823349a438b7b8fa966dfd520c1b/adafruit_matrixportal/matrix.py#L180

and I see that there is a rotation getter/setter for the FrameBufferDisplay:
https://circuitpython.readthedocs.io/en/latest/shared-bindings/framebufferio/index.html#framebufferio.FramebufferDisplay.rotation

**Comment by makermelissa** [comment]
Oh yeah, it looks like I pasted the wrong link. That's the one I meant to paste. :)

**Comment by kmatch98** [comment]
From the CircuitPython call today, I just learned that TileGrid has options for transposing to her rotation, maybe that is an easier solution for text.
