### ISSUE TITLE
duplicate code in library files - potential refactor needed

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_MatrixPortal#65]
actions failure with details on duplicated sections is [here](https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/runs/2031406555?check_suite_focus=true#step:11:32)

We want to avoid having duplicated code if possible. One way to avoid might be to move the duplicated sections into a shared super class.

**Comment by makermelissa** [comment]
We might be able to fix this by using `**kwargs`.
