### ISSUE TITLE
Improve network json_path checking

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_MatrixPortal#8]
Currently it requires the json_path to be in a tuple because it was trying to allow the path itself to be in a tuple for flexibility. However, I have had this trip up @jedgarpark and @PaintYourDragon, so I think I need to make this more user friendly and less flexible (i.e. the path itself will have to be a list and can't be a tuple). Unless somebody has done something against the usual examples, it shouldn't harm any code.

**Comment by tannewt** [comment]
So how are you changing it? Requiring a list?

**Comment by makermelissa** [comment]
I'm thinking about having it check the structure better instead of guessing like it does now. So if it's just a flat list, it can enclose in a tuple and if it's a tuple of list with list elements inside, then it should be good to go.

**Comment by tannewt** [comment]
Ah, because it can be a sequence or a sequence of sequences. :+1:
