### ISSUE TITLE
Scroll bmp and text together

### ISSUE THREAD

**Issue by tejasxo** [adafruit/Adafruit_CircuitPython_MatrixPortal#82]
Hi all,
I'm trying to create a stock ticker where the company logo is displayed to the left of some price info.
I would like to scroll both the bmp and the text data. Is there any way I can do this?

**Comment by makermelissa** [comment]
Unfortunately, I don't believe that's not possible with the current features in this library. I would suggest using the network portion of the library only (see https://learn.adafruit.com/creating-projects-with-the-circuitpython-matrixportal-library) and then you can create the graphics portion yourself so you can make the best use of memory.
