### ISSUE TITLE
Add BLE support to the library

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_MatrixPortal#85]
I have a feedback item with this:

> Matrixportal code for LED matrix does not coexist with BLE. I used the sample BLE code for other projects and it works well. But when i try to integrate it with this code, it fails.
> ```
> matrixportal = MatrixPortal(status_neopixel=board.NEOPIXEL, debug=False)
> ```
> The error is:
> ```
> Traceback (most recent call last):
> File "code.py", line 60, in
> File "adafruit_matrixportal/matrixportal.py", line 110, in __init__
> File "adafruit_matrixportal/network.py", line 66, in __init__
> File "adafruit_portalbase/wifi_coprocessor.py", line 57, in __init__
> ValueError: ESP_BUSY in use
> ```

I'm not sure if the Library will work fine if the esp object is initialized first and passed in or if any changes would be necessary. Either way, it makes sense that we should have an example.

**Comment by mak3r** [comment]
I agree. It's misleading that the docs show how to use the matrixportal board with BLE but you cannot use the MatrixPortal API with BLE. The MatrixPortal API actually indicates that it is tightly coupled with WiFi https://learn.adafruit.com/adafruit-matrixportal-m4/matrixportal-library-overview and if you dig into the docs, you can see that it's not possible to use BLE and WiFi simultaneously, you have to choose one. So, the solution is going to be to use a lower level library like the GraphicsBase. Or, use displayio directly.

**Comment by rebtop** [comment]
I am so glad i found this post.
I have been trying for several weeks to find a fix for this combination.
It is fruitless. I will be careful from now on what i use for sample code.

**Comment by justmobilize** [comment]
@makermelissa and @dhalbert what would your thought be on adding a `connection_mode` to the `init` and allowing the user to select `WiFi`, `Bluetooth` or `None`?

We could start without Bluetooth, allowing the user to initialize that themselves. And then add the BT support in a later PR?

**Comment by dhalbert** [comment]
On MatrixPortal M4, the AirLift coprocessor has to be reset to switch to BLE mode. https://github.com/adafruit/Adafruit_CircuitPython_AirLift has code to do this, but that particular library doesn't mix very well with the WiFi libraries.

Rather than a `connection_mode`, I'm thinking separate booleans for `wifi` and `ble`, and complain if they are both set if they can't be used simultaneously. It's possible that on some future board both could be available simultaneously. Also then you don't have to introduce an enum with possible values, etc.

I do think the tight tie to wifi should be relaxed, since once we have good ESP32-S3 BLE support, that will become more popular.

**Comment by justmobilize** [comment]
A boolean makes sense as well. I could start with just one for `enable_wifi` and default it to true... And when False, pass None in for `network`, which `PortalBase` already handles

**Comment by justmobilize** [comment]
@rebtop are you willing to grab the code from #97 and see if you can run your example?

**Comment by rebtop** [comment]
Justin,  Yes.
I responded on Github
________________________________

**Comment by rebtop** [comment]
Justin

took awhile but here is code for BLE that works with M4 MatrixPortal code

Bob

________________________________

**Comment by rebtop** [comment]
Justin Myers

________________________________

**Comment by rebtop** [comment]
Justin
Sorry it took so long.
Bob
#     contributed by Robert Black  with the support of the people at Adafruit especially Justin
#     simple script to utilize MatrtixPortal code and BLE
import time
import board
import terminalio
from adafruit_matrixportal.matrixportal import MatrixPortal
#  --------------------------------------------------------------------

import busio
from digitalio import DigitalInOut
from adafruit_ble import BLERadio
from adafruit_ble.advertising.standard import ProvideServicesAdvertisement
from adafruit_ble.services.nordic import UARTService
from adafruit_esp32spi import adafruit_esp32spi
from adafruit_airlift.esp32 import ESP32
# ------------------------------------------------------------------------

esp32 = ESP32()
adapter = esp32.start_bluetooth()
ble = BLERadio(adapter)
uart = UARTService()
advertisement = ProvideServicesAdvertisement(uart)
ble.start_advertising(advertisement)
read_count = 1
received_text = " "
raw_bytes = " "
end_it = 0

# --- Display setup ---
matrixportal = MatrixPortal(status_neopixel=board.NEOPIXEL, debug=True, use_wifi=False)

# Create a new label  text 
matrixportal.add_text(
    text_font=terminalio.FONT,
    text_position=(0, (matrixportal.graphics.display.height // 2) - 1),
    scrolling=True,
)
SCROLL_DELAY = 0.03

def scroll_screen():
#        set text
    matrixportal.set_text(text)
#        Scroll it
    matrixportal.scroll_text(SCROLL_DELAY)

def read_uart():
    global read_count, rt, end_it, text
    raw_bytes = uart.read(20)
    received_text = raw_bytes.decode().strip()
    rt = received_text
#    read uart  UTF-8
    while rt == "." or rt == "..": 
#        received . to end program
        text = "Ending......"
#        scroll text
        scroll_screen()
        end_it = end_it + 1
        if end_it == 3:
            endit()
    return (received_text, rt)
while True:
#    connected message
    text = "connected - waiting for input"
    while not ble.connected:
#     waiting to connect
        text = "waiting to connect"
        read_count = 0
        scroll_screen()
# CONNECTED
    while ble.connected:
#    has one input been detected?
        if not read_count ==1:
            text = "connected - waiting for input"
        scroll_screen()    
        while uart.in_waiting: 
#          one input detected
            read_count = 1
            received_text, rt = read_uart() #received_text1 = read_uart()
            text = rt

            if not uart.in_waiting:
                scroll_screen()
    while ble.connected:
        text = "connected - waiting for input"
        scroll_screen()    `
